version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-backend
    ports:
      - "8080:8080"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
