name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Download dependencies
        run: go mod download
      - name: Run linter
        run: make lint

  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod download

      - name: Build and run docker container
        run: make docker-run

      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to start..."
          for i in {1..20}; do
            if curl -s -f http://localhost:8080/ &> /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            sleep 3
          done
          echo "Server failed to start after 60 seconds."
          exit 1

      - name: Run Integration Tests
        run: make test